### PR TITLE
Issue 59: specify n_cpus

### PR DESCRIPTION
**Pull request by maamari**
Allow for specification of n_cpus in splash() method

### CODE REVIEW

**Comment by syasini** [comment]
@maamari: Looks great Karime! Well done. 

I can't merge this because it's directly going to the master. got back a commit, start a new feature branch, rebase master, push that to your fork, then submit another pull request. 

PS: I love how you caught n_cpu=0! I definitely would have missed that myself :)

**Comment by maamari** [comment]
Okay sweet, so should I submit the pull request from my n_cpus branch to develop?

**Comment by syasini** [comment]
Yes! 

If it allows you to push to a new branch called n_cpus it's even better, but it's probably not possible on your end...

**Comment by maamari** [comment]
Okay cool, sounds good. Yeah, I couldn't find a way to add a n_cpus branch to the main repo

**Pull request closed without merging**
